import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import TopNav from '../components/TopNav'
import BottomNav from '../components/BottomNav'
const about = () => {
  return (
    <div>
    <Head>
        <title>About me - Wavewalker Freelacing Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#111827" />
        <link rel="icon" href="../images/favicon.svg" />
        <link rel="stylesheet" href="style.css" />
      </Head>
      <TopNav />
      <section className="w-full text-white">
      <section id="bottom-navigation" className="md:hidden block fixed inset-x-0 bottom-0 z-10 bg-gray-800 shadow">
        <div id="tabs" className="flex justify-between space-x-10 py-2 px-4">
          <Link href="/" ><a className="w-full bg-blue-600 bg-opacity-0 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
            <span className="tab tab-home block text-xs">Home</span>
          </a></Link>
          <Link href="/about"><a className="w-full bg-blue-600 bg-opacity-100 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="tab tab-kategori block text-xs">About</span>
          </a></Link>
          <Link href="/pricing"><a className="w-full bg-blue-600 bg-opacity-0 hover:bg-opacity-30 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            <span className="tab tab-whishlist block text-xs">Pricing</span>
          </a></Link>
          <Link href="/contact"><a className="w-full bg-blue-600 bg-opacity-0 hover:bg-opacity-30 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
            </svg>
            <span className="tab tab-account block text-xs">Contact</span>
          </a></Link>
        </div>
      </section>
    </section>
        {/* <header className="text-gray-400 bg-gray-800 bg-opacity-50 body-font">
            <div className="container mx-auto flex flex-wrap px-1 py-3 flex-col md:flex-row items-center">
              <a href="https://t.me/wavewa1ker" className="flex title-font font-medium items-center text-white mb-4 md:mb-0">
                <svg width={28} height={28} viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <line x1="8.3033" y1="22.6967" x2="32.274" y2="46.6674" stroke="#3B82F6" strokeWidth={15} />
                  <line x1="8.3033" y1="58.6967" x2="32.274" y2="82.6674" stroke="#3B82F6" strokeWidth={15} />
                  <line x1="21.6967" y1="46.6967" x2="54.9307" y2="13.4627" stroke="#3B82F6" strokeWidth={15} />
                  <line x1="21.6967" y1="82.6967" x2="54.9307" y2="49.4627" stroke="#3B82F6" strokeWidth={15} />
                  <line x1="45.3033" y1="12.6967" x2="78.5373" y2="45.9307" stroke="#3B82F6" strokeWidth={15} />
                  <line x1="45.3033" y1="48.6967" x2="78.5373" y2="81.9307" stroke="#3B82F6" strokeWidth={15} />
                  <line x1="67.6967" y1="45.7383" x2="91.7383" y2="21.6967" stroke="#3B82F6" strokeWidth={15} />
                  <line x1="67.6967" y1="81.7383" x2="91.7383" y2="57.6967" stroke="#3B82F6" strokeWidth={15} />
                </svg>
                <span className="ml-3 text-xl">Wavewalker</span>
              </a>
              <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center">
                <a href="/" className="mr-2 text-gray-200 py-1 px-2 bg-white bg-opacity-0 hover:bg-opacity-10 hover:text-white rounded tracking-wide transition-colors duration-300 ease-in-out ">Home</a>
                <a href="/about" className=" mr-2 text-gray-200 py-1 px-2 bg-white bg-opacity-0 hover:bg-opacity-10 hover:text-white rounded tracking-wide transition-colors duration-300 ease-in-out ">About</a>
                <a href="/pricing" className=" mr-5 text-gray-200 py-1 px-2 bg-white bg-opacity-0 hover:bg-opacity-10 hover:text-white rounded tracking-wide transition-colors duration-300 ease-in-out ">Pricing</a>
              </nav>
              <a href="/contact"><button className="clicky inline-flex items-center  border-0 py-1 px-3 focus:outline-none bg-blue-700 text-gray-100 bg-opacity-80 hover:bg-opacity-100 rounded text-base mt-4 md:mt-0 transition-colors duration-300 ease-in-out">Contact</button></a> 
            </div>
          </header> */}
          <section className="text-gray-400 bg-gray-900 body-font">
            <div className="container px-5 py-24 mx-auto flex flex-col">
              <div className="lg:w-4/6 mx-auto">
                <div className="rounded-lg h-64 overflow-hidden">
                  <img alt="content" className="object-cover object-center h-full w-full" src="/images/businessCard.png" />
                </div>
                <div className="flex flex-col sm:flex-row mt-10">
                  <div className="sm:w-1/3 text-center sm:pr-8 sm:py-8">
                    <div className="w-20 h-20 rounded-full inline-flex items-center justify-center bg-gray-800 text-gray-600 rounded-full overflow-hidden  ">
                      <img className="object-cover object-center" src="/images/pp.jpg" alt="" />
                    </div>
                    <div className="flex flex-col items-center text-center justify-center">
                      <h2 className="font-medium title-font mt-1 text-white text-lg">Manmeet Singh</h2>
                      <div className="w-12 h-1 bg-blue-500 rounded mt-2 mb-4" />
                      <p className="text-base text-gray-400">A web developer and graphic designer who has a passion in creating powerful, functional, and user-friendly websites.</p>
                    </div>
                  </div>
                  <div className="sm:w-2/3 sm:pl-8 sm:py-8 sm:border-l border-gray-800 sm:border-t-0 border-t mt-4 pt-4 sm:mt-0 text-center sm:text-left">
                    {/* component */}
                    <div className="max-w-2xl text-white mx-auto rounded">
                      <div id="accordion-collapse" data-accordion="collapse">
                        <h2 id="accordion-collapse-heading-1">
                          <button type="button" className="bg-blue-700 bg-opacity-70 text-white flex items-center justify-between p-5 w-full font-medium text-left border border-gray-800 text-gray-100 rounded-t-xl" data-accordion-target="#accordion-collapse-body-1" aria-expanded="true" aria-controls="accordion-collapse-body-1">
                            <span className="text-white">Focus on creativity experience success</span>
                            <svg data-accordion-icon className="w-6 h-6 shrink-0 text-white rotate-180" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                              <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
                            </svg>
                          </button>
                        </h2>
                        <div id="accordion-collapse-body-1" aria-labelledby="accordion-collapse-heading-1">
                          <div className="p-5 bg-gray-800 bg-opacity-20 border border-gray-800 border-t-0">
                            <p className="text-white">A website development and design solution, with a focus on creativity, experience, and success.
                              Freelance web developer and designer who specializes in creating powerful, functional, and user-friendly websites. I have also worked with international clients. I hold good communication skills. When my favorite work comes, I take it as an opportunity and make sure to give my best!
                            </p>
                          </div>
                        </div>
                        <h2 id="accordion-collapse-heading-2">
                          <button type="button" className="bg-blue-700 bg-opacity-70 text-white flex items-center justify-between p-5 w-full font-medium border border-gray-800 text-left text-white" data-accordion-target="#accordion-collapse-body-2" aria-expanded="false" aria-controls="accordion-collapse-body-2">
                            <span className="text-white">Specialized in user-friendly websites</span>
                            <svg data-accordion-icon className="w-6 h-6 shrink-0 text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                              <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
                            </svg>
                          </button>
                        </h2>
                        <div id="accordion-collapse-body-2" className="hidden" aria-labelledby="accordion-collapse-heading-2">
                          <div className="p-5 bg-gray-800 bg-opacity-20 border border-gray-800 border-b-0">
                            <p className="mb-2 text-white">I take pride in my work, and am always looking for opportunities to learn more. I have created many successful websites for various clients across the world. I am confident that I can make your website too! I've been designing for only about 5 years now, but I haven't looked back since! Being a freelancer web designer, I believe, it is the greatest ability bestowed more on people to take control of their own life issues and design their own world for themselves.</p>
                          </div>
                        </div>
                        <h2 id="accordion-collapse-heading-3">
                          <button type="button" className="bg-blue-700 bg-opacity-70 text-white flex items-center border border-gray-800 justify-between p-5 w-full font-medium text-left text-white" data-accordion-target="#accordion-collapse-body-3" aria-expanded="false" aria-controls="accordion-collapse-body-3">
                            <span className="text-white">You've found what you're looking for!</span>
                            <svg data-accordion-icon className="w-6 h-6 shrink-0 text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                              <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
                            </svg>
                          </button>
                        </h2>
                        <div id="accordion-collapse-body-3" className="hidden" aria-labelledby="accordion-collapse-heading-3">
                          <div className="p-5 bg-gray-800 bg-opacity-20 border border-gray-800 border-t-0">
                            <p className="mb-2 text-white">I have a strong understanding of web design principles that are followed by most of the talented designers out there today. If you're looking for someone to help with your website or branding needs look no further!
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* PROJECTS */}
          <section className="text-gray-400 bg-gray-900 body-font">
            <div className="text-center mb-4">
              <h1 className="text-4xl font-medium text-center title-font text-white mb-2">Portfolio</h1>
              <p className="text-base leading-relaxed xl:w-2/4 lg:w-3/4 mx-auto">A representation of works I have created</p>
              <div className="flex mt-4 justify-center">
                <div className="w-16 h-1 rounded-full bg-blue-500 inline-flex" />
              </div>
            </div>
            <div className="swiper mySwiper">
              <div className="swiper-wrapper">
                <div className="swiper-slide">
                  <section className="text-gray-400 bg-gray-900 body-font">
                    <div className="container px-5 py-24 mx-auto">
                      <div className="flex flex-wrap justify-center -mx-4 -mb-10 text-center">
                        <div className="sm:w-1/2 mb-10 px-4">
                          <div className="rounded-lg h-64 overflow-hidden"><img alt="content" className="object-cover object-center h-full w-full" src="/images/mv.png" /> </div>
                          <h2 className="tracking-widest text-sm title-font mt-6  text-blue-500 mb-1">WORDPRESS WEBSITE </h2>
                          <h2 className="title-font text-2xl font-medium text-white mb-3 tracking-wide ">Market Victors</h2>
                          <p className="leading-relaxed text-base">The most popular CMS in the world, WordPress is empowering more than 60 million websites for individuals and organizations. NOT to sound conceited! I made this website myself. In fact, I can help you with your site too. Just get your ideas ready! We'll end up with a perfect piece.</p>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
                <div className="swiper-slide">
                  <section className="text-gray-400 bg-gray-900 body-font">
                    <div className="container px-5 py-24 mx-auto">
                      <div className="flex flex-wrap justify-center -mx-4 -mb-10 text-center">
                        <div className="sm:w-1/2 mb-10 px-4">
                          <div className="rounded-lg h-64 overflow-hidden"><img alt="content" className="object-cover object-center h-full w-full border border-gray-800 border-opacity-40 " src="/images/site.png" /> </div>
                          <h2 className="tracking-widest text-sm title-font mt-6  text-blue-500 mb-1">WEB DEVELOPMENT </h2>
                          <h2 className="title-font text-2xl font-medium text-white mb-3 tracking-wide ">My Portfolio Website</h2>
                          <p className="leading-relaxed text-base">The navigation of my portfolio site is very easy to understand. You can click on any section that you are interested in and it will take you there instantly. It features a well balanced animations, CSS3, HTML5, and other cool stuff to give you the best experience possible.</p>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
                <div className="swiper-slide">
                  <section className="text-gray-400 bg-gray-900 body-font">
                    <div className="container px-5 py-24 mx-auto">
                      <div className="flex flex-wrap justify-center -mx-4 -mb-10 text-center">
                        <div className="sm:w-1/2 mb-10 px-4">
                          <div className="rounded-lg h-64 overflow-hidden"><img alt="content" className="object-cover mx-auto object-center h-full w-full" src="/images/dcmv.png" /> </div>
                          <h2 className="tracking-widest text-sm title-font mt-6  text-blue-500 mb-1">DISCORD SERVERS </h2>
                          <h2 className="title-font text-2xl font-medium text-white mb-3 tracking-wide ">Market Victors</h2>
                          <p className="leading-relaxed text-base">Discord is the most popular in gamers. It's also possible to use Discord for non-gaming purposes too - like marketing, design collaboration or remote work teams. Setup your discord server with various features such as verification system, reaction roles, channels and much more with me .</p>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
                {/* 
              <div class="swiper-slide">
              <section class="text-gray-400 bg-gray-900 body-font">
              <div class="container px-5 py-24 mx-auto">
              <div class="flex flex-wrap justify-center -mx-4 -mb-10 text-center">
                 <div class="sm:w-1/2 mb-10 px-4">
                    <div class="rounded-lg h-64 overflow-hidden"><img alt="content" class="object-contain mx-auto object-center h-full" src="/images/UIaboutpage.png"> </div>
                    <h2 class="tracking-widest text-sm title-font mt-6  text-blue-500 mb-1">UI/UX </h2>
                    <h2 class="title-font text-2xl font-medium text-white mb-3 tracking-wide ">About Page</h2>
                    <p class="leading-relaxed text-base">About page is the section of your website that a visitor sees while visit. It's a crucial piece of content for your site. I made this page using my UI/UX skills, I've designed the page in such a way that it can be easily navigated. Also it is responsive so that people using different devices can use it.</p>
                 </div>
              </div>
              </div>
              </section>
              </div> */}
                <div className="swiper-slide">
                  <section className="text-gray-400 bg-gray-900 body-font">
                    <div className="container px-5 py-24 mx-auto">
                      <div className="flex flex-wrap justify-center -mx-4 -mb-10 text-center">
                        <div className="sm:w-1/2 mb-10 px-4">
                          <div className="rounded-lg h-64 overflow-hidden"><img alt="content" className="object-cover object-center h-full w-full" src="/images/businessCard.png" /> </div>
                          <h2 className="tracking-widest text-sm title-font mt-6  text-blue-500 mb-1 uppercase"> GraphicS WITH FIGMA</h2>
                          <h2 className="title-font text-2xl font-medium text-white mb-3 tracking-wide ">A Business Card Design</h2>
                          <p className="leading-relaxed text-base">A business card is an essential part of marketing your product or service. With a modern and clean design, it will make you stand out among the crowd! The content of the text is not too long. Even though it doesn't have much content, it surely gets across the meaning!</p>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
                <div className="swiper-slide">
                  <section className="text-gray-400 bg-gray-900 body-font">
                    <div className="container px-5 py-24 mx-auto">
                      <div className="flex flex-wrap justify-center -mx-4 -mb-10 text-center">
                        <div className="sm:w-1/2 mb-10 px-4">
                          <div className="rounded-lg h-64 overflow-hidden"><img alt="content" className="object-cover mx-auto object-center h-full w-full" src="/images/fms.png" /> </div>
                          <h2 className="tracking-widest text-sm title-font mt-6  text-blue-500 mb-1">FRONTEND CHALLENGES</h2>
                          <h2 className="title-font text-2xl font-medium text-white mb-3 tracking-wide ">Frontend Mentor Solutions</h2>
                          <p className="leading-relaxed text-base">Every day has a challenge waiting to be solved! Helping newcomers in the field by posting solutions to specific problems</p>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
                <div className="swiper-slide">
                  <section className="text-gray-400 bg-gray-900 body-font">
                    <div className="container px-5 py-24 mx-auto">
                      <div className="flex flex-wrap justify-center -mx-4 -mb-10 text-center">
                        <div className="sm:w-1/2 mb-10 px-4">
                          <div className="rounded-lg h-64 overflow-hidden"><img alt="content" className="object-cover mx-auto object-center h-full w-full" src="/images/DCsas.png" /> </div>
                          <h2 className="tracking-widest text-sm title-font mt-6  text-blue-500 mb-1">DISCORD SERVERS </h2>
                          <h2 className="title-font text-2xl font-medium text-white mb-3 tracking-wide ">Second Action Studio</h2>
                          <p className="leading-relaxed text-base">Discord is the most popular in gamers. It's also possible to use Discord for non-gaming purposes too - like marketing, design collaboration or remote work teams. Setup your discord server with various features such as verification system, reaction roles, channels and much more with me .</p>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
                {/* <div class="swiper-slide"><section class="text-gray-400 bg-gray-900 body-font"><div class="container px-5 py-24 mx-auto"> <div class="flex flex-wrap justify-center -mx-4 -mb-10 text-center"><div class="sm:w-1/2 mb-10 px-4"> <div class="rounded-lg h-64 overflow-hidden"><img alt="content" class="object-cover object-center h-full w-full" src="/images/"> </div><h2 class="tracking-widest text-sm title-font mt-6  text-blue-500 mb-1">GRAPHIC DESIGN </h2> <h2 class="title-font text-2xl font-medium text-white mb-3 tracking-wide ">Party Card</h2> <p class="leading-relaxed text-base">I'll collaborate with you for a custom design solution that will work for you! Need any help in business cards and event banners, then don't hesitate to get in touch with me! You can see my recent work on my website and if you'd like to hire me then thanks from the bottom of my heart :)</p></div></div></div></section></div>*/}
                <div className="swiper-slide">
                  <section className="text-gray-400 bg-gray-900 body-font">
                    <div className="container px-5 py-24 mx-auto">
                      <div className="flex flex-wrap justify-center -mx-4 -mb-10 text-center">
                        <div className="sm:w-1/2 mb-10 px-4">
                          <div className="rounded-lg h-64 overflow-hidden"><img alt="content" className="object-cover object-center h-full w-full" src="/images/palamarprops.png" /> </div>
                          <h2 className="tracking-widest text-sm title-font mt-6  text-blue-500 mb-1">WEB DEVELOPMENT</h2>
                          <h2 className="title-font text-2xl font-medium text-white mb-3 tracking-wide ">Real Estate Website</h2>
                          <p className="leading-relaxed text-base"> I've recently made a Real Estate Website. I coded it in such a way to provide a user-friendly, easy-to-navigate and responsive experience. It contains all the features that are necessary to make it attractive. The contact forms are easy to use and the call to actions are very attractive on the website. </p>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
              </div>
              <div className="swiper-button-next" />
              <div className="swiper-button-prev" />
              <div className="swiper-pagination" />
            </div>
          </section>
          {/* CERTIFICATE */}
          <section className="text-gray-400 bg-gray-900 body-font">
            <div className="container px-5 py-24 mx-auto">
              <div className="text-center mb-20">
                <h1 className="text-4xl font-medium text-center title-font text-white mb-2">Certifications</h1>
                <p className="text-base leading-relaxed xl:w-2/4 lg:w-3/4 mx-auto">Certificates of Achievement in the process. A representation of skills certifications that I have earned</p>
                <div className="flex mt-4 justify-center">
                  <div className="w-16 h-1 rounded-full bg-blue-500 inline-flex" />
                </div>
              </div>
              <div className="flex flex-wrap -mx-4 -mb-10 text-center">
                <div className="sm:w-1/2 mb-10 px-4">
                  <div className="rounded-lg h-64 overflow-hidden">
                    <img alt="content" className="object-contain object-center h-full w-full" src="images/HackerRankCSS.png" />
                  </div>
                  <h2 className="title-font text-2xl font-medium text-white mt-6 mb-3">HackerRank</h2>
                  <p className="leading-relaxed text-base">Their assessments are an excellent way to expose yourself to new technologies and languages while simultaneously learning how your skills can best be utilized by potential employers outside of any one company or industry.</p>
                  {/* <button class="flex mx-auto mt-6 text-white bg-blue-500 border-0 py-2 px-5 focus:outline-none hover:bg-blue-600 rounded">Button</button> */}
                </div>
                <div className="sm:w-1/2 mb-10 px-4">
                  <div className="rounded-lg h-64 overflow-hidden">
                    <img alt="content" className="object-contain object-center h-full w-full" src="images/mimo.png" />
                  </div>
                  <h2 className="title-font text-2xl font-medium text-white mt-6 mb-3">MIMO</h2>
                  <p className="leading-relaxed text-base">Mimo offers interactive lessons on popular programming languages like HTML, JS, CSS, Python and SQL. You can also find tutorials on web development tools. Mimo will teach you how to code in no time.</p>
                  {/* <button class="flex mx-auto mt-6 text-white bg-blue-500 border-0 py-2 px-5 focus:outline-none hover:bg-blue-600 rounded">Button</button> */}
                </div>
              </div>
            </div>
          </section>
          {/*  
        <section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
          <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
              <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <span class="inline-block py-1 px-2 rounded bg-blue-800 bg-opacity-50 text-blue-200 text-xs font-medium tracking-widest">CERTIFICATE</span>
                <h1 class="text-white mt-2 text-3xl title-font font-medium mb-4">HackerRank</h1>
                <p class="leading-relaxed mb-4">A few weeks ago I decided to take HackerRank's Coding Challenge and I got a Certificate of Achievement in the process. Their assessments are an excellent way to expose yourself to new technologies and languages while simultaneously learning how your skills can best be utilized by potential employers outside of any one company or industry.</p>
              </div>
              <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded-lg" src="images/HackerRankCSS.png">
            </div>
          </div>
        </section>
        
        <section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
          <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
              <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-48 object-cover object-center rounded-lg" src="images/MimoWebDev.png">
              <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
                <span class="inline-block py-1 px-2 rounded bg-blue-800 text-blue-200 bg-opacity-50 text-xs font-medium tracking-widest">CERTIFICATE</span>
                <h1 class="text-white mt-2 text-3xl title-font font-medium mb-1">MIMO</h1>
                <p class="leading-relaxed">Mimo offers interactive lessons on popular programming languages like HTML, JS, CSS, Python and SQL. You can also find tutorials on web development tools. Mimo will teach you how to code in no time.</p>
        
              </div>
            </div>
          </div>
        </section>*/}
          {/*  
        <section class="text-gray-400 bg-gray-900 body-font">
          <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
              <h1 class="flex-grow sm:pr-16 text-4xl font-medium title-font text-white">Alone we can do so little, together we can do so much.</h1>
              <button class="clicky flex-shrink-0 bg-blue-700 text-gray-100 bg-opacity-80 hover:bg-opacity-100 py-2 px-8 focus:outline-none hover:bg-blue-600 rounded text-lg mt-10 sm:mt-0 transition-colors duration-300 ease-in-out">Let's Talk</button>
            </div>
          </div>
        </section>*/}
          <section className="text-gray-400 bg-blue-600 body-font">
            <div className="container px-5 py-24 mx-auto">
              <div className="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
                <lord-icon src="https://cdn.lordicon.com/xqnbvely.json" trigger="hover" colors="primary:#ffffff,secondary:#1663c7" style={{width: '250px', height: '250px'}} className="transform-gpu rotate-180">
                </lord-icon>
                <h1 className="flex-grow sm:pr-16 text-4xl font-medium title-font text-white">Alone we can do so little, together we can do so much.</h1>
                <button className="clicky flex-shrink-0 bg-gray-100 ubu-bold text-gray-900 bg-opacity-100 hover:bg-opacity-90 py-2 px-8 focus:outline-none rounded text-lg mt-10 sm:mt-0 transition-colors duration-300 ease-in-out">
                  Let's Talk 
                  <svg xmlns="http://www.w3.org/2000/svg" className="inline ml-1 mb-1 h-6 w-6 text-gray-900" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15 15l-2 5L9 9l11 4-5 2zm0 0l5 5M7.188 2.239l.777 2.897M5.136 7.965l-2.898-.777M13.95 4.05l-2.122 2.122m-5.657 5.656l-2.12 2.122" />
                  </svg>
                </button>
              </div>
            </div>
          </section>
          <footer className="text-gray-400 bg-gray-800 bg-opacity-40 body-font">
            <div className="container py-2 mx-auto flex items-center sm:flex-row flex-col">
              <nav className="md:hidden lg:hidden flex flex-wrap items-center text-base m-2">
                <a href="/index" className="mr-5 text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">Home</a>
                <a href="/about" className="mr-5 text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">About</a>
                <a href="/pricing" className="mr-5 text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">Pricing</a>
                <a href="/contact" className="text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">Contact</a>
              </nav>
              <p className="text-sm text-gray-400 sm:ml-4 sm:pl-4 sm:py-2 sm:mt-0 mt-4">© 2021 wavewalker —
                <a href="https://www.fiverr.com/wavewalker777" className="ml-1 sign font-bold text-xl text-gray-300 tracking-wide" target="_blank" rel="noopener noreferrer">ManmeetSingh</a>
              </p>
              <span className="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
                <a className="text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
                  <svg fill="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} className="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z" />
                  </svg>
                </a>
                <a className="ml-3 text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
                  <svg fill="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} className="w-7 h-7" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
                    <path d="m20.665 3.717-17.73 6.837c-1.21.486-1.203 1.161-.222 1.462l4.552 1.42 10.532-6.645c.498-.303.953-.14.579.192l-8.533 7.701h-.002l.002.001-.314 4.692c.46 0 .663-.211.921-.46l2.211-2.15 4.599 3.397c.848.467 1.457.227 1.668-.785l3.019-14.228c.309-1.239-.473-1.8-1.282-1.434z" />
                  </svg>
                </a>
                <a className="ml-3 text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
                  <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} className="w-5 h-5" viewBox="0 0 24 24">
                    <rect width={20} height={20} x={2} y={2} rx={5} ry={5} />
                    <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01" />
                  </svg>
                </a>
                <a className="ml-3 text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
                  <svg fill="currentColor" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0} className="w-5 h-5" viewBox="0 0 24 24">
                    <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z" />
                    <circle cx={4} cy={4} r={2} stroke="none" />
                  </svg>
                </a>
              </span>
            </div>
          </footer>
<script src="https://cdn.lordicon.com/xdjxvujz.js"></script>
<script src="https://cdn.tailwindcss.com"></script>
<script type="text/javascript" src='../crisp-init.js'></script>
<script type="text/javascript" src='../swiper-init.js'></script>
<script type="text/javascript" src='../swiper-bundle.min.js'></script>

    </div>
  )
}

export default about