import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import TopNav from '../components/TopNav'
import BottomNav from '../components/BottomNav'
const contact = () => {
  return (
    <div>
        <Head>
    <title>Wavewalker Freelacing Services</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="theme-color" content="#111827" />
    <link rel="icon" href="../images/favicon.svg" />
    <link rel="stylesheet" href="style.css" />
  </Head>
  <TopNav />
  <section className="w-full text-white">
      <section id="bottom-navigation" className="md:hidden block fixed inset-x-0 bottom-0 z-10 bg-gray-800 shadow">
        <div id="tabs" className="flex justify-between space-x-10 py-2 px-4">
          <Link href="/" ><a className="w-full bg-blue-600 bg-opacity-0 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
            <span className="tab tab-home block text-xs">Home</span>
          </a></Link>
          <Link href="/about"><a className="w-full bg-blue-600 bg-opacity-0 hover:bg-opacity-30 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="tab tab-kategori block text-xs">About</span>
          </a></Link>
          <Link href="/pricing"><a className="w-full bg-blue-600 bg-opacity-0 hover:bg-opacity-30 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            <span className="tab tab-whishlist block text-xs">Pricing</span>
          </a></Link>
          <Link href="/contact"><a className="w-full bg-blue-600 bg-opacity-100 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
            </svg>
            <span className="tab tab-account block text-xs">Contact</span>
          </a></Link>
        </div>
      </section>
    </section>

  {/* <header className="text-gray-400 bg-gray-800 bg-opacity-50 body-font">
    <div className="container mx-auto flex flex-wrap px-1 py-3 flex-col md:flex-row items-center">
      <a href="https://t.me/wavewa1ker" className="flex title-font font-medium items-center text-white mb-4 md:mb-0">
        <svg width={28} height={28} viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <line x1="8.3033" y1="22.6967" x2="32.274" y2="46.6674" stroke="#3B82F6" strokeWidth={15} />
          <line x1="8.3033" y1="58.6967" x2="32.274" y2="82.6674" stroke="#3B82F6" strokeWidth={15} />
          <line x1="21.6967" y1="46.6967" x2="54.9307" y2="13.4627" stroke="#3B82F6" strokeWidth={15} />
          <line x1="21.6967" y1="82.6967" x2="54.9307" y2="49.4627" stroke="#3B82F6" strokeWidth={15} />
          <line x1="45.3033" y1="12.6967" x2="78.5373" y2="45.9307" stroke="#3B82F6" strokeWidth={15} />
          <line x1="45.3033" y1="48.6967" x2="78.5373" y2="81.9307" stroke="#3B82F6" strokeWidth={15} />
          <line x1="67.6967" y1="45.7383" x2="91.7383" y2="21.6967" stroke="#3B82F6" strokeWidth={15} />
          <line x1="67.6967" y1="81.7383" x2="91.7383" y2="57.6967" stroke="#3B82F6" strokeWidth={15} />
        </svg>
        <span className="ml-3 text-xl">Wavewalker</span>
      </a>
      <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center">
        <a href="/" className="mr-2 text-gray-200 py-1 px-2 bg-white bg-opacity-0 hover:bg-opacity-10 hover:text-white rounded tracking-wide transition-colors duration-300 ease-in-out ">Home</a>
        <a href="/about.html" className=" mr-2 text-gray-200 py-1 px-2 bg-white bg-opacity-0 hover:bg-opacity-10 hover:text-white rounded tracking-wide transition-colors duration-300 ease-in-out ">About</a>
        <a href="/pricing.html" className=" mr-5 text-gray-200 py-1 px-2 bg-white bg-opacity-0 hover:bg-opacity-10 hover:text-white rounded tracking-wide transition-colors duration-300 ease-in-out ">Pricing</a>
      </nav>
      <a href="/contact.html"><button className="clicky inline-flex items-center  border-0 py-1 px-3 focus:outline-none bg-blue-700 text-gray-100 bg-opacity-80 hover:bg-opacity-100 rounded text-base mt-4 md:mt-0 transition-colors duration-300 ease-in-out">Contact</button></a> 
    </div>
  </header> */}
  <section className="text-gray-900 bg-gray-900 body-font">
    <div className="container px-5 py-24 mx-auto flex flex-wrap items-center">
      <div className="lg:w-3/5 md:w-1/2 md:pr-16 lg:pr-0 pr-5">
        <h1 className="title-font font-medium text-3xl text-white">Feedbacks or any queries <br /> Kindly fill up this form.</h1>
        <p className="leading-relaxed my-4 text-white">Need more ways to connect? I got you covered</p>
        <div className="flex md:ml-auto md:mr-0 mx-auto items-center flex-shrink-0 space-x-2 pr-5">
          <a href="https://forms.gle/MuMHfiUgctdermxi9" className="bg-gray-50 shadow-md inline-flex py-3 px-5 rounded-lg items-center hover:bg-gray-200 transition-colors duration-500 ease-in-out focus:outline-none">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-gray-800" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={0}>
              <path d="M6 12C6 15.3137 8.68629 18 12 18C14.6124 18 16.8349 16.3304 17.6586 14H12V10H21.8047V14H21.8C20.8734 18.5645 16.8379 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C15.445 2 18.4831 3.742 20.2815 6.39318L17.0039 8.68815C15.9296 7.06812 14.0895 6 12 6C8.68629 6 6 8.68629 6 12Z" fill="currentColor" />
            </svg>
            <span className="ml-4 flex items-start flex-col leading-none">
              {/* <span class="text-xs text-gray-600 mb-1 ">Hassle free contact</span> */}
              <span className="title-font font-medium">Forms</span>
            </span>
          </a>
          <a href="https://www.fiverr.com/wavewalker777" className="bg-gray-50 shadow-md inline-flex py-3 px-5 rounded-lg items-center hover:bg-gray-200 transition-colors duration-500 ease-in-out focus:outline-none">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
            </svg>
            <span className="ml-4 flex items-start flex-col leading-none">
              {/* <span class="text-xs text-gray-600 mb-1">Get a quote</span> */}
              <span className="title-font font-medium">Fiverr</span>
            </span>
          </a>
          <a href="mailto:royalmarine995@gmail.com" className="bg-gray-50 shadow-md inline-flex py-3 px-5 rounded-lg items-center hover:bg-gray-200 transition-colors duration-500 ease-in-out focus:outline-none">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
            <span className="ml-4 flex items-start flex-col leading-none">
              {/* <span class="text-xs text-gray-600 mb-1">Get a quote</span> */}
              <span className="title-font font-medium">Email</span>
            </span>
          </a>
        </div>
      </div>
      <div className="flex flex-col w-full bg-gray-900 lg:w-1/3 md:ml-auto md:mt-0 md:py-8 md:w-1/2 mt-8">
        <form action="https://formsubmit.co/royalmarine995@gmail.com" method="POST">
          <input name="_subject" type="hidden" defaultValue="New submission- A new visitor wants to contact you!" />
          <h1 className="title-font font-medium capitalize mb-4 text-3xl text-gray-50">get in touch</h1>
          {/* <p class="text-gray-400 leading-relaxed mb-5 text-sm"> */}
          <div className="relative mb-4"><label className="text-gray-400 text-sm leading-7" htmlFor="name">Your Name <span className="pop-semi text-red-500">*</span></label> <input name="Sender'sﾠName" className="ease-in-out rounded transition-colors bg-gray-800 border border-gray-700 duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-600 outline-none px-3 py-1 text-base text-gray-200 w-full leading-8" id="name" required /></div>
          <div className="relative mb-4"><label className="text-gray-400 text-sm leading-7" htmlFor="email">Your Email<span className="pop-semi text-red-500">*</span></label> <input name="Sender'sﾠEmailﾠAddress" type="email" className="ease-in-out rounded transition-colors bg-gray-800 border border-gray-700 duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-600 outline-none px-3 py-1 text-base text-gray-200 w-full leading-8" id="email" required /></div>
          <div className="relative mb-4"><label className="text-gray-400 text-sm leading-7" htmlFor="phone">Your Phone</label> <input name="ContactﾠNumber" type="tel" className="ease-in-out rounded transition-colors bg-gray-800 border border-gray-700 duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-600 outline-none px-3 py-1 text-base text-gray-200 w-full leading-8" id="phone" /></div>
          <div className="relative mb-4"><label className="text-gray-400 text-sm leading-7" htmlFor="message">Leave Your Message<span className="pop-semi text-red-500">*</span></label> <textarea className="ease-in-out rounded transition-colors bg-gray-800 border border-gray-700 duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-600 outline-none px-3 py-1 text-base text-gray-200 w-full h-32 leading-6 placeholder:text-gray-600 resize-none" id="message" name="MessageﾠBody" placeholder="How may I help you?" required defaultValue={""} /></div>
          <input name="_captcha" type="hidden" defaultValue="false" /> <input name="_next" type="hidden" defaultValue="thank-you.htm/" />
          <button className="clicky inline-flex items-center border-0 py-2 px-5 focus:outline-none bg-blue-700 text-gray-100 bg-opacity-80 hover:bg-opacity-100 rounded text-base mt-4 md:mt-0 transition-colors duration-300 ease-in-out" type="submit">Submit</button> <button className="px-6 capitalize focus:outline-none text-lg border-0 duration-500 hover:text-blue-400 hover:underline text-blue-500" type="reset" onclick="alerty()">reset</button>
          <p className="text-xs mt-3 text-gray-300">Fields with asterisk(<span className="pop-semi text-red-500">*</span>) are required to send response to your text.<br />Sit back and relax your data will be kept safe.
          </p></form>
      </div>
    </div>
  </section>
  <footer className="text-gray-400 bg-gray-800 bg-opacity-40 body-font">
    <div className="container py-2 mx-auto flex items-center sm:flex-row flex-col">
      <nav className="md:hidden lg:hidden flex flex-wrap items-center text-base m-2">
        <a href="/index.html" className="mr-5 text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">Home</a>
        <a href="/about.html" className="mr-5 text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">About</a>
        <a href="/pricing.html" className="mr-5 text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">Pricing</a>
        <a href="/contact.html" className="text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">Contact</a>
      </nav>
      <p className="text-sm text-gray-400 sm:ml-4 sm:pl-4 sm:py-2 sm:mt-0 mt-4">© 2021 wavewalker —
        <a href="https://www.fiverr.com/wavewalker777" className="ml-1 sign font-bold text-xl text-gray-300 tracking-wide" target="_blank" rel="noopener noreferrer">ManmeetSingh</a>
      </p>
      <span className="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
        <a className="text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
          <svg fill="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} className="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z" />
          </svg>
        </a>
        <a className="ml-3 text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
          <svg fill="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} className="w-7 h-7" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
            <path d="m20.665 3.717-17.73 6.837c-1.21.486-1.203 1.161-.222 1.462l4.552 1.42 10.532-6.645c.498-.303.953-.14.579.192l-8.533 7.701h-.002l.002.001-.314 4.692c.46 0 .663-.211.921-.46l2.211-2.15 4.599 3.397c.848.467 1.457.227 1.668-.785l3.019-14.228c.309-1.239-.473-1.8-1.282-1.434z" />
          </svg>
        </a>
        <a className="ml-3 text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
          <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} className="w-5 h-5" viewBox="0 0 24 24">
            <rect width={20} height={20} x={2} y={2} rx={5} ry={5} />
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01" />
          </svg>
        </a>
        <a className="ml-3 text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
          <svg fill="currentColor" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0} className="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z" />
            <circle cx={4} cy={4} r={2} stroke="none" />
          </svg>
        </a>
      </span>
    </div>
  </footer>

<script src="https://cdn.lordicon.com/xdjxvujz.js"></script>
<script src="https://cdn.tailwindcss.com"></script>
<script type="text/javascript" src='../crisp-init.js'></script>
<script type="text/javascript" src='../swiper-init.js'></script>
<script type="text/javascript" src='../swiper-bundle.min.js'></script>
    </div>
  )
}

export default contact