import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import TopNav from '../components/TopNav'
import BottomNav from '../components/BottomNav'
const pricing = () => {
  return (
    <div>
        <Head>
    <title>Wavewalker Freelacing Services</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="theme-color" content="#111827" />
    <link rel="icon" href="../images/favicon.svg" />
    <link rel="stylesheet" href="style.css" />
  </Head>
  <TopNav />
  <section className="w-full text-white">
      <section id="bottom-navigation" className="md:hidden block fixed inset-x-0 bottom-0 z-10 bg-gray-800 shadow">
        <div id="tabs" className="flex justify-between space-x-10 py-2 px-4">
          <Link href="/" ><a className="w-full bg-blue-600 bg-opacity-0 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
            <span className="tab tab-home block text-xs">Home</span>
          </a></Link>
          <Link href="/about"><a className="w-full bg-blue-600 bg-opacity-0 hover:bg-opacity-30 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="tab tab-kategori block text-xs">About</span>
          </a></Link>
          <Link href="/pricing"><a className="w-full bg-blue-600 bg-opacity-100 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            <span className="tab tab-whishlist block text-xs">Pricing</span>
          </a></Link>
          <Link href="/contact"><a className="w-full bg-blue-600 bg-opacity-0 hover:bg-opacity-30 focus:bg-opacity-100 justify-center inline-block text-center py-2 rounded">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 inline-block mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
            </svg>
            <span className="tab tab-account block text-xs">Contact</span>
          </a></Link>
        </div>
      </section>
    </section>

{/* <header className="text-gray-400 bg-gray-800 bg-opacity-50 body-font">
    <div className="container mx-auto flex flex-wrap px-1 py-3 flex-col md:flex-row items-center">
      <a href="https://t.me/wavewa1ker" className="flex title-font font-medium items-center text-white mb-4 md:mb-0">
        <svg width={28} height={28} viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <line x1="8.3033" y1="22.6967" x2="32.274" y2="46.6674" stroke="#3B82F6" strokeWidth={15} />
          <line x1="8.3033" y1="58.6967" x2="32.274" y2="82.6674" stroke="#3B82F6" strokeWidth={15} />
          <line x1="21.6967" y1="46.6967" x2="54.9307" y2="13.4627" stroke="#3B82F6" strokeWidth={15} />
          <line x1="21.6967" y1="82.6967" x2="54.9307" y2="49.4627" stroke="#3B82F6" strokeWidth={15} />
          <line x1="45.3033" y1="12.6967" x2="78.5373" y2="45.9307" stroke="#3B82F6" strokeWidth={15} />
          <line x1="45.3033" y1="48.6967" x2="78.5373" y2="81.9307" stroke="#3B82F6" strokeWidth={15} />
          <line x1="67.6967" y1="45.7383" x2="91.7383" y2="21.6967" stroke="#3B82F6" strokeWidth={15} />
          <line x1="67.6967" y1="81.7383" x2="91.7383" y2="57.6967" stroke="#3B82F6" strokeWidth={15} />
        </svg>
        <span className="ml-3 text-xl">Wavewalker</span>
      </a>
      <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center">
        <a href="/" className="mr-2 text-gray-200 py-1 px-2 bg-white bg-opacity-0 hover:bg-opacity-10 hover:text-white rounded tracking-wide transition-colors duration-300 ease-in-out ">Home</a>
        <a href="/about" className=" mr-2 text-gray-200 py-1 px-2 bg-white bg-opacity-0 hover:bg-opacity-10 hover:text-white rounded tracking-wide transition-colors duration-300 ease-in-out ">About</a>
        <a href="/pricing" className=" mr-5 text-gray-200 py-1 px-2 bg-white bg-opacity-0 hover:bg-opacity-10 hover:text-white rounded tracking-wide transition-colors duration-300 ease-in-out ">Pricing</a>
      </nav>
      <a href="/contact"><button className="clicky inline-flex items-center  border-0 py-1 px-3 focus:outline-none bg-blue-700 text-gray-100 bg-opacity-80 hover:bg-opacity-100 rounded text-base mt-4 md:mt-0 transition-colors duration-300 ease-in-out">Contact</button></a> 
    </div>
  </header> */}
  {/* benefits */}
  <div className="bg-gray-900 text-gray-100">
    <div className="container px-6 py-8 mx-auto">
      <div className="xl:items-center xl:-mx-8 xl:flex">
        <div className="w-full flex flex-col items-center xl:mx-8">
          <h1 className="text-3xl font-medium text-gray-100 capitalize lg:text-4xl ">Benefits received!</h1>
          <div className="mt-1">
            <span className="inline-block w-40 h-1 bg-blue-500 rounded-full" />
            <span className="inline-block w-3 h-1 mx-1 bg-blue-500 rounded-full" />
            <span className="inline-block w-1 h-1 bg-blue-500 rounded-full" />
          </div>
          <p className=" text-gray-200">The reasons to choose </p>
        </div>
        <div className="flex-1 xl:mx-8">
          <div className="mt-8 space-y-8 md:-mx-4 md:flex md:items-center md:justify-center md:space-y-0 xl:mt-0">
          </div>
        </div>
      </div>
    </div>
  </div>
  {/* bene desc */}
  {/* features */}
  <section className=" text-gray-400 bg-gray-900 body-font">
    <div className="container px-5 pb-24 mx-auto">
      <div className="flex flex-wrap lg:w-4/5 sm:mx-auto sm:mb-2 -mx-2">
        <div className="p-2 sm:w-1/2 w-full">
          <div className="bg-gray-800 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} className="text-green-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14" />
              <path d="M22 4L12 14.01l-3-3" />
            </svg>
            <span className="title-font font-medium text-white">Flexible schedule and plan making</span>
          </div>
        </div>
        <div className="p-2 sm:w-1/2 w-full">
          <div className="bg-gray-800 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} className="text-green-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14" />
              <path d="M22 4L12 14.01l-3-3" />
            </svg>
            <span className="title-font font-medium text-white">Frequent testing</span>
          </div>
        </div>
        <div className="p-2 sm:w-1/2 w-full">
          <div className="bg-gray-800 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} className="text-green-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14" />
              <path d="M22 4L12 14.01l-3-3" />
            </svg>
            <span className="title-font font-medium text-white">Rectification &amp; maintenance of project</span>
          </div>
        </div>
        <div className="p-2 sm:w-1/2 w-full">
          <div className="bg-gray-800 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} className="text-green-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14" />
              <path d="M22 4L12 14.01l-3-3" />
            </svg>
            <span className="title-font font-medium text-white">Timely completions</span>
          </div>
        </div>
        <div className="p-2 sm:w-1/2 w-full">
          <div className="bg-gray-800 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} className="text-green-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14" />
              <path d="M22 4L12 14.01l-3-3" />
            </svg>
            <span className="title-font font-medium text-white">Consistent with the work</span>
          </div>
        </div>
        <div className="p-2 sm:w-1/2 w-full">
          <div className="bg-gray-800 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} className="text-green-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14" />
              <path d="M22 4L12 14.01l-3-3" />
            </svg>
            <span className="title-font font-medium text-white">Proper guidance </span>
          </div>
        </div>
        <div className="p-2 sm:w-1/2 w-full">
          <div className="bg-gray-800 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} className="text-green-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14" />
              <path d="M22 4L12 14.01l-3-3" />
            </svg>
            <span className="title-font font-medium text-white">After sales services </span>
          </div>
        </div>
        <div className="p-2 sm:w-1/2 w-full">
          <div className="bg-gray-800 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} className="text-green-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14" />
              <path d="M22 4L12 14.01l-3-3" />
            </svg>
            <span className="title-font font-medium text-white">99.99% quick response</span>
          </div>
        </div>
      </div>
    </div>
  </section>
  {/* <section class="text-gray-400 bg-gray-900 body-font">
<div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
  <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
    <h1 class="title-font sm:text-5xl text-4xl mb-4 font-medium text-white">Flexible schedule & plan making</h1>
     <p class="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
    <div class="flex justify-center">
      <button class="inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg">Button</button>
      <button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button>
    </div> 
  </div>
  <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
    <img class="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
  </div>
</div>
</section>
<section class="text-gray-400 bg-gray-900 body-font">
<div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
<div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
  <img class="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
</div>
<div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
  <h1 class="title-font sm:text-5xl text-4xl mb-4 font-medium text-white">Timely completions</h1>
   <p class="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
  <div class="flex justify-center">
    <button class="inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg">Button</button>
    <button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button>
  </div> 
</div>
</div>
</section>
<section class="text-gray-400 bg-gray-900 body-font">
<div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
  <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
    <h1 class="title-font sm:text-5xl text-4xl mb-4 font-medium text-white">Quick response to queries</h1>
     <p class="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
    <div class="flex justify-center">
      <button class="inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg">Button</button>
      <button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button>
    </div> 
  </div>
  <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
    <img class="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
  </div>
</div>
</section>
<section class="text-gray-400 bg-gray-900 body-font">
<div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
<div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
  <img class="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
</div>
<div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
  <h1 class="title-font sm:text-5xl text-4xl mb-4 font-medium text-white">Consistent with the work    </h1>
   <p class="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
  <div class="flex justify-center">
    <button class="inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg">Button</button>
    <button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button>
  </div> 
</div>
</div>
</section>
<section class="text-gray-400 bg-gray-900 body-font">
<div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
  <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
    <h1 class="title-font sm:text-5xl text-4xl mb-4 font-medium text-white">Rectification & maintenance of project</h1>
    <p class="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
    <div class="flex justify-center">
      <button class="inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg">Button</button>
      <button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button>
    </div> 
  </div>
  <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
    <img class="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
  </div>
</div>
</section>
<section class="text-gray-400 bg-gray-900 body-font">
<div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
<div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
  <img class="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
</div>
<div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
  <h1 class="title-font sm:text-5xl text-4xl mb-4 font-medium text-white">Proper guidance</h1>
  p class="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
  <div class="flex justify-center">
    <button class="inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg">Button</button>
    <button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button>
  </div> 
</div>
</div>
</section> */}
  {/* price */}
  <div className="bg-gray-900 text-gray-100">
    <div className="container px-6 py-8 mx-auto">
      <div className="xl:items-center xl:-mx-8 xl:flex">
        <div className="sm:w-full md:w-1/5 flex flex-col items-center xl:items-start xl:mx-8">
          <h1 className="text-3xl font-medium text-gray-100 capitalize lg:text-4xl ">Pricing Plans</h1>
          <div className="mt-1">
            <span className="inline-block w-40 h-1 bg-blue-500 rounded-full" />
            <span className="inline-block w-3 h-1 mx-1 bg-blue-500 rounded-full" />
            <span className="inline-block w-1 h-1 bg-blue-500 rounded-full" />
          </div>
          <p className="mt-4 font-medium text-gray-200 ">You can get all access by selecting your plan!</p>
        </div>
        <div className="flex-1 xl:mx-8">
          <div className="mt-8 space-y-8 md:-mx-4 md:flex md:items-center md:justify-center md:space-y-0 xl:mt-0">
            <div className="max-w-sm mx-auto border border-gray-500 rounded-lg bg-gray-800 bg-opacity-50 md:mx-4">
              <div className="p-6">
                <h1 className="text-sm font-medium text-gray-200 capitalize tracking-widest">DISCORD SERVER SETUP</h1>
                <h2 className="mt-4 text-4xl font-medium text-gray-200">$50<span className="text-base p-2 relative bottom-3 font-medium line-through">$150</span></h2>
                <button className="clicky w-full px-4 py-2 mt-6 tracking-wide text-white capitalize transition-colors duration-200 transform bg-blue-600 rounded-md hover:bg-blue-500 focus:outline-none">
                  <a href="https://www.fiverr.com/share/qlj6QX">Choose plan</a>
                </button>
              </div>
              <hr className="border-gray-600" />
              <div className="p-6">
                <h1 className="text-lg font-medium text-gray-200 capitalize lg:text-xl ">What's included:</h1>
                <div className="mt-8 space-y-2">
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Custom theme &amp; roles.</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Verification system</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Moderation bots</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Mobile app</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Ticket raising system</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="max-w-sm mx-auto border border-gray-500 rounded-lg bg-gray-800 bg-opacity-80 md:mx-4">
              <div className="p-6">
                <h1 className="text-sm font-medium text-gray-200 capitalize  tracking-widest">FULL WEBSITE CREATION</h1>
                <h2 className="mt-4 text-4xl font-medium text-gray-200">$85<span className="text-base p-2 relative bottom-3 font-medium line-through">$250</span></h2>
                <button className="clicky w-full px-4 py-2 mt-6 tracking-wide text-white capitalize transition-colors duration-200 transform bg-blue-600 rounded-md hover:bg-blue-500 focus:outline-none">
                  <a href="https://www.fiverr.com/share/1zbLep">Choose plan</a>
                </button>
              </div>
              <hr className="border-gray-600" />
              <div className="p-6">
                <h1 className="text-lg font-medium text-gray-200 capitalize lg:text-xl ">What's included:</h1>
                <div className="mt-8 space-y-2">
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Responsive Design</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Social media integration</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Content Upload</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Source Code (Premium)</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Portfolio/StartUp/Business</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="max-w-sm mx-auto border border-gray-500 rounded-lg bg-gray-800 bg-opacity-50 md:mx-4">
              <div className="p-6">
                <h1 className="text-sm font-medium text-gray-200 capitalize  tracking-widest">CREATIVE DESIGNING</h1>
                <h2 className="mt-4 text-4xl font-medium text-gray-200">$75<span className="text-base p-2 relative bottom-3 font-medium line-through">$250</span></h2>
                <button className="clicky w-full px-4 py-2 mt-6 tracking-wide text-white capitalize transition-colors duration-200 transform bg-blue-600 rounded-md hover:bg-blue-500 focus:outline-none">
                  <a href="https://www.fiverr.com/share/EPmDDe">Choose plan</a>
                </button>
              </div>
              <hr className="border-gray-600" />
              <div className="p-6">
                <h1 className="text-lg font-medium text-gray-200 capitalize lg:text-xl ">What's included:</h1>
                <div className="mt-8 space-y-2">
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">UI Design with Figma</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Banners
                      ∀
                      topics</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Make business cards</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Unique designs</span>
                  </div>
                  <div className="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span className="mx-4 text-gray-200">Make NFT Collection</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer className="text-gray-400 bg-gray-800 bg-opacity-40 body-font">
    <div className="container py-2 mx-auto flex items-center sm:flex-row flex-col">
      <nav className="md:hidden lg:hidden flex flex-wrap items-center text-base m-2">
        <a href="/index" className="mr-5 text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">Home</a>
        <a href="/about" className="mr-5 text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">About</a>
        <a href="/pricing" className="mr-5 text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">Pricing</a>
        <a href="/contact" className="text-gray-300 border-b border-dashed border-gray-300 border-opacity-0 hover:border-opacity-100 hover:text-white transition-colors duration-300 ease-in-out">Contact</a>
      </nav>
      <p className="text-sm text-gray-400 sm:ml-4 sm:pl-4 sm:py-2 sm:mt-0 mt-4">© 2021 wavewalker —
        <a href="https://www.fiverr.com/wavewalker777" className="ml-1 sign font-bold text-xl text-gray-300 tracking-wide" target="_blank" rel="noopener noreferrer">ManmeetSingh</a>
      </p>
      <span className="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
        <a className="text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
          <svg fill="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} className="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z" />
          </svg>
        </a>
        <a className="ml-3 text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
          <svg fill="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} className="w-7 h-7" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
            <path d="m20.665 3.717-17.73 6.837c-1.21.486-1.203 1.161-.222 1.462l4.552 1.42 10.532-6.645c.498-.303.953-.14.579.192l-8.533 7.701h-.002l.002.001-.314 4.692c.46 0 .663-.211.921-.46l2.211-2.15 4.599 3.397c.848.467 1.457.227 1.668-.785l3.019-14.228c.309-1.239-.473-1.8-1.282-1.434z" />
          </svg>
        </a>
        <a className="ml-3 text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
          <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} className="w-5 h-5" viewBox="0 0 24 24">
            <rect width={20} height={20} x={2} y={2} rx={5} ry={5} />
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01" />
          </svg>
        </a>
        <a className="ml-3 text-gray-400 hover:text-blue-500 transition-colors duration-300 ease-in-out  ">
          <svg fill="currentColor" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={0} className="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z" />
            <circle cx={4} cy={4} r={2} stroke="none" />
          </svg>
        </a>
      </span>
    </div>
  </footer>
  <script src="https://cdn.lordicon.com/xdjxvujz.js"></script>
<script src="https://cdn.tailwindcss.com"></script>
<script type="text/javascript" src='../crisp-init.js'></script>
<script type="text/javascript" src='../swiper-init.js'></script>
<script type="text/javascript" src='../swiper-bundle.min.js'></script> 
    </div>
  )
}

export default pricing